2018-08-1420:40:11,755ERROR:Exceptionon/search[GET][inc:\users\manolomon\desktop\webpython\venv\lib\site-packages\flask\app.py:1761]
yruan@yahoo.com
Traceback(mostrecentcalllast):
File"c:\users\manolomon\desktop\webpython\venv\lib\site-packages\urllib3\connection.py",line171,in_new_conn
(self._dns_host,self.port),self.timeout,**extra_kw)
File"c:\users\manolomon\desktop\webpython\venv\lib\site-packages\urllib3\util\connection.py",line79,increate_connection
raiseerr
jtorkbob@gmail.com
dkrishna@icloud.com
File"c:\users\manolomon\desktop\webpython\venv\lib\site-packages\urllib3\util\connection.py",line69,increate_connection
sock.connect(sa)
ConnectionRefusedError:[WinError10061]Nosepuedeestablecerunaconexi�nyaqueelequipodedestinodeneg�expresamentedichaconexi�n
Duringhandlingoftheaboveexception,anotherexceptionoccurred:
pontipak@yahoo.com
Traceback(mostrecentcalllast):
File"c:\users\manolomon\desktop\webpython\venv\lib\site-packages\elasticsearch\connection\http_urllib3.py",line171,inperform_request
response=self.pool.urlopen(method,url,body,retries=False,headers=request_headers,**kw)
File"c:\users\manolomon\desktop\webpython\venv\lib\site-packages\urllib3\util\retry.py",line343,inincrement
raisesix.reraise(type(error),error,_stacktrace)
murdocj@hotmail.com
File"c:\users\manolomon\desktop\webpython\venv\lib\site-packages\urllib3\packages\six.py",line686,inreraise
raisevalue
danneng@optonline.net
kenja@icloud.com
File"c:\users\manolomon\desktop\webpython\venv\lib\site-packages\urllib3\connectionpool.py",line354,in_make_request
conn.request(method,url,**httplib_request_kw)
ghost@verizon.net
File"C:\Users\Manolomon\AppData\Local\Programs\Python\Python37-32\lib\http\client.py",line1229,inrequest
self._send_request(method,url,body,headers,encode_chunked)
fmerges@sbcglobal.net
File"C:\Users\Manolomon\AppData\Local\Programs\Python\Python37-32\lib\http\client.py",line1275,in_send_request
self.endheaders(body,encode_chunked=encode_chunked)
File"C:\Users\Manolomon\AppData\Local\Programs\Python\Python37-32\lib\http\client.py",line1224,inendheaders
self._send_output(message_body,encode_chunked=encode_chunked)
elmer@comcast.net
File"C:\Users\Manolomon\AppData\Local\Programs\Python\Python37-32\lib\http\client.py",line1016,in_send_output
self.send(msg)
scarolan@yahoo.com
File"c:\users\manolomon\desktop\webpython\venv\lib\site-packages\urllib3\connection.py",line196,inconnect
conn=self._new_conn()
File"c:\users\manolomon\desktop\webpython\venv\lib\site-packages\urllib3\connection.py",line180,in_new_conn
self,"Failedtoestablishanewconnection:%s"%e)
rgarton@yahoo.com
urllib3.exceptions.NewConnectionError:<urllib3.connection.HTTPConnectionobjectat0x06019070>:Failedtoestablishanewconnection:[WinError10061]Nosepuedeestablecerunaconexi�nyaqueelequipodedestinodeneg�expresamentedichaconexi�n
Duringhandlingoftheaboveexception,anotherexceptionoccurred:
podmaster@live.com
heidrich@sbcglobal.net
Traceback(mostrecentcalllast):
File"c:\users\manolomon\desktop\webpython\venv\lib\site-packages\flask\app.py",line2292,inwsgi_app
response=self.full_dispatch_request()
File"c:\users\manolomon\desktop\webpython\venv\lib\site-packages\flask_login\utils.py",line261,indecorated_view
returnfunc(*args,**kwargs)
kludge@att.net
File"C:\Users\Manolomon\Desktop\WebPython\app\main\routes.py",line144,insearch
current_app.config['POSTS_PER_PAGE'])
File"C:\Users\Manolomon\Desktop\WebPython\app\models.py",line15,insearch
ids,total=query_index(cls.__tablename__,expression,page,per_page)
itstatus@hotmail.com
File"C:\Users\Manolomon\Desktop\WebPython\app\search.py",line23,inquery_index
'from':(page-1)*per_page,'size':per_page})
rgarton@yahoo.com
File"c:\users\manolomon\desktop\webpython\venv\lib\site-packages\elasticsearch\client\utils.py",line76,in_wrapped
returnfunc(*args,params=params,**kwargs)
File"c:\users\manolomon\desktop\webpython\venv\lib\site-packages\elasticsearch\client\__init__.py",line655,insearch
doc_type,'_search'),params=params,body=body)
File"c:\users\manolomon\desktop\webpython\venv\lib\site-packages\elasticsearch\transport.py",line318,inperform_request
status,headers_response,data=connection.perform_request(method,url,params,body,headers=headers,ignore=ignore,timeout=timeout)
File"c:\users\manolomon\desktop\webpython\venv\lib\site-packages\elasticsearch\connection\http_urllib3.py",line180,inperform_request
raiseConnectionError('N/A',str(e),e)
elasticsearch.exceptions.ConnectionError:ConnectionError(<urllib3.connection.HTTPConnectionobjectat0x06019070>:Failedtoestablishanewconnection:[WinError10061]Nosepuedeestablecerunaconexi�nyaqueelequipodedestinodeneg�expresamentedichaconexi�n)causedby:NewConnectionError(<urllib3.connection.HTTPConnectionobjectat0x06019070>:Failedtoestablishanewconnection:[WinError10061]Nosepuedeestablecerunaconexi�nyaqueelequipodedestinodeneg�expresamentedichaconexi�n)
dunstan@verizon.net
2018-08-1420:41:49,821INFO:Microblogstartup[inC:\Users\Manolomon\Desktop\WebPython\app\__init__.py:77]
2018-08-1420:52:59,780INFO:Microblogstartup[inC:\Users\Manolomon\Desktop\WebPython\app\__init__.py:77]
mccurley@mac.com
2018-08-1421:35:14,481INFO:Microblogstartup[inC:\Users\Manolomon\Desktop\WebPython\app\__init__.py:77]
2018-08-1421:36:35,654ERROR:Exceptionon/search[GET][inc:\users\manolomon\desktop\webpython\venv\lib\site-packages\flask\app.py:1761]
grdschl@mac.com
thrymm@gmail.com
Traceback(mostrecentcalllast):
File"c:\users\manolomon\desktop\webpython\venv\lib\site-packages\elasticsearch\connection\http_urllib3.py",line186,inperform_request
self._raise_error(response.status,raw_data)
File"c:\users\manolomon\desktop\webpython\venv\lib\site-packages\elasticsearch\connection\base.py",line125,in_raise_error
raiseHTTP_EXCEPTIONS.get(status_code,TransportError)(status_code,error_message,additional_info)
elasticsearch.exceptions.NotFoundError:NotFoundError(404,'index_not_found_exception','nosuchindex')
2018-08-1421:37:41,431INFO:Microblogstartup[inC:\Users\Manolomon\Desktop\WebPython\app\__init__.py:77]
